server:
  port: 9901
spring:
  application:
    name: '@artifactId@'
  redis:
    database: 0
    host: ${REDIS_SERVER:localhost}
    port: ${REDIS_PORT:6379}
    password: ''
  profiles:
    active: @profiles.active@
  # mysql数据库配置
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:localhost}:${MYSQL_PORT:8080}/${MYSQL_DATABASE:cloud_rbac}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

  security:
    oauth2:
      jwt:
        signKey: Fdi6UdDA