server:
  port: 9900

spring:
  application:
    name: @artifactId@
  datasource:
    url: jdbc:mysql://${mysql.server:localhost}:${mysql.port:8080}/${MYSQL_DATABASE:cloud_rbac}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server:localhost}:${nacos.port:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml
        shared-configs:
          -application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  redis:
    database: 0
    host: ${redis.server:localhost}
    port: ${redis.port:6379}
    password: ''

  profiles:
    active: ${env:test}
